config/routes.rb
Rails.application.routes.draw do
  resources :states

  resources :diagnostics do
    collection { post :import }
  end

  get 'administrator/index'

  get 'office_worker/index'

  get 'home/index'

  resources :office_worker do
    resources :appointments
  end
  
  resources :administrator do
    resources :physicians
    resources :diagnostics
  end
  
  resources :appointments do
    resources :physicians
    resources :patients
  end

  resources :physicians do
    resources :patients
    resources :appointments
  end

  resources :patients do
    resources :physicians
    resources :appointments
    resources :states
  end
  
  

   root 'home#index'

end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  def index
    @physicians = Physician.all
    @diagnostics = Diagnostic.all
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/views/administrator/index.html.erb
<h1>Administrator</h1>
<br>
<h2>Current Physicians</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Hired</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= physician.email %></td>
        <td><%= physician.phone %></td>
        <td><%= physician.hired %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>
<br>
<br>
<br>
<h2>Diagnostic Codes</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostics.each do |diagnostic| %>
      <tr>
        <td><%= diagnostic.name %></td>
        <td><%= diagnostic.abbreviation %></td>
        <td><%= link_to 'Edit', edit_diagnostic_path(diagnostic) %></td>
        <td><%= link_to 'Destroy', diagnostic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnostic', new_diagnostic_path %>