config/routes.rb
Rails.application.routes.draw do
  resources :states

  resources :diagnostics do
    collection { post :import }
  end

  get 'administrator/index'

  get 'office_worker/index'

  get 'home/index'

  resources :office_worker do
    resources :appointments
  end
  
  resources :administrator do
    resources :physicians
    resources :diagnostics
  end
  
  resources :appointments do
    resources :physicians
    resources :patients
  end

  resources :physicians do
    resources :patients
    resources :appointments
  end

  resources :patients do
    resources :physicians
    resources :appointments
    resources :states
  end
  
  

   root 'home#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
  belongs_to :state
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :zip, presence: true, length: { is: 5 }, numericality: { only_integer: true}
  validates :phone, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :address, :city, :state_id, :zip, :phone, :email)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <br>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <br>
  <div class="field">
    <%= f.label :state_id %><br>
     <%= f.collection_select(:state_id, State.all, :id, :name) %>
  </div>
  <br>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <br>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<br>
<br>
<br>

<h1>Edit Your Information</h1>

<%= render 'form' %>

<br>
<a href="javascript:history.go(-1)">Back</a>

app/views/patients/index.html.erb
<br>
<br>
<h1>Current Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.city %></td>
        <td><%= patient.state.abbreviation %></td>
        <td><%= patient.zip %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.email %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Yourself', new_patient_path %>

app/views/patients/new.html.erb
<br>
<br>
<br>
<h1>Enter Your Information</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<H1>

  <%= @patient.name %>
</h1>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @patient.state.name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @patient.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>
<%= link_to 'Edit Patient', edit_patient_path(@patient) %> ||
<a href="javascript:history.go(-1)">Back</a>
<br>

<br>
<br>
<h1>Your Appointments</h1>
<%= link_to 'New Appointment', new_appointment_path %>
<br>
<br>
<h2>Today</h2>

<table>
  <thead>
    <tr>
      <th>Physician</th>
      <th>App date</th>
      <th>App time</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient.appointments.each do |appointment| %>
	<% if (appointment.app_date == Date.today)%>
	<% if (((appointment.app_time - Time.now) * 24) <=8)%>
      <tr>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.app_time.strftime("%H:%M") %></td>
        <td><%= appointment.description %></td>
      </tr>
	  <% else %>
      <tr>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.app_time.in_time_zone("Central Time (US & Canada)").strftime("%H:%M") %></td>
        <td><%= appointment.description %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	  
    <% end %>
	<% end %>
	<% end %>
  </tbody>
</table>

<br>
<h2>Upcoming</h2>

<table>
  <thead>
    <tr>
      <th>Physician</th>
      <th>App date</th>
      <th>App time</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient.appointments.each do |appointment| %>
	<% if (appointment.app_date != Date.today) %>
      <tr>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.app_time.strftime("%H:%M") %></td>
        <td><%= appointment.description %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	  <% else %>
    <% end %>
	<% end %>
  </tbody>
</table>

<br>