config/routes.rb
Rails.application.routes.draw do
  resources :states

  resources :diagnostics do
    collection { post :import }
  end

  get 'administrator/index'

  get 'office_worker/index'

  get 'home/index'

  resources :office_worker do
    resources :appointments
  end
  
  resources :administrator do
    resources :physicians
    resources :diagnostics
  end
  
  resources :appointments do
    resources :physicians
    resources :patients
  end

  resources :physicians do
    resources :patients
    resources :appointments
  end

  resources :patients do
    resources :physicians
    resources :appointments
    resources :states
  end
  
  

   root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
  belongs_to :diagnostic
  validates :app_time, uniqueness: {scope: [:app_date, :physician_id]}, presence: true
  validates :description, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :physician_id, :app_date, :app_time, :description, :notes, :diagnostic_id, :cost)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Select a Patient<br>
    <%= f.collection_select(:patient_id, Patient.all, :id, :name) %>
  </div>
  <br>
  <div class="field">
    Select A Physician<br>
   <%= f.collection_select(:physician_id, Physician.all, :id, :name) %>
   
  </div>
  <br>
  <div class="field">
   Choose A Date<br>
    <%= f.text_field :app_date %>
  </div>
  <br>
  <div class="field">
    Select A Time<br>
    <%= f.time_select :app_time, {:minute_step => 30, :ampm => true, start_hour: 8, end_hour: 16} %>
  </div>
  <br>
  <div class="field">
    Enter A Brief Description<br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
  <a href="javascript:history.go(-1)">Back</a>
  <br>
  <br>
  <br>
  <h2><strong>Office Use Only</strong></h2>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <br>
  <div class="field">
    <%= f.label :diagnostic_id %><br>
    <%= f.collection_select(:diagnostic_id, Diagnostic.all, :id, :name) %>
  </div>
  <br>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <br>
  <br>
  
<% end %>

app/views/appointments/edit.html.erb
<br>
<br>
<br>
<h1>Editing appointment</h1>

<%= render 'form' %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Physician</th>
      <th>App date</th>
      <th>App time</th>
      <th>Description</th>
      <th>Notes</th>
      <th>Diagnostic</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.app_time %></td>
        <td><%= appointment.description %></td>
        <td><%= appointment.notes %></td>
        <td><%= appointment.diagnostic.abbreviation %></td>
        <td><%= appointment.cost %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<br>
<br>
<br>
<h1>Create a New Appointment</h1>

<%= render 'form' %>

app/views/appointments/show.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.name %>
</p>

<p>
  <strong>App date:</strong>
  <%= @appointment.app_date %>
</p>

<p>
  <strong>App time:</strong>
  <%= @appointment.app_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>



<%= link_to 'Edit', edit_appointment_path(@appointment) %> 
<br>
<br>
<h2>Office Use Only</h2>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Diagnostic:</strong>
  <%= @appointment.diagnostic.abbreviation %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @appointment.cost %>
</p>